type: string
enum:
  - STATUS_UNKNOWN
  - STATUS_WAITING_FOR_DEPLOYMENT
  - STATUS_DEPLOYING
  - STATUS_RUNNING
  - STATUS_FAILED
  - STATUS_WAITING_FOR_UNDEPLOYMENT
  - STATUS_UNDEPLOYING
  - STATUS_UNDEPLOYMENT_FAILED
  - STATUS_DELETED
default: STATUS_UNKNOWN
example: STATUS_UNKNOWN
